test_1_ (test_libcmd.CMDTest1) ... ok
test_0_init (test_confparse.CPTest1) ... ok
test_1_find_config (test_confparse.CPTest1) ... ok
test_2_load (test_confparse.CPTest1) ... ok
test_3_set_string (test_confparse.CPTest1) ... ok
test_4_lists (test_confparse.CPTest1) ... ERROR
test_5_copy (test_confparse.CPTest1) ... FAIL
test_6_commit (test_confparse.CPTest1) ... FAIL
test_1_ (test_confparse.CPTest2) ... ERROR
test_2_ (test_confparse.CPTest2) ... ok
test_1_read_dict (test_confparse2.CP2Test1) ... ok
test_1_read_dict_int (test_confparse2.CP2Test1) ... ok
test_1_read_list (test_confparse2.CP2Test1) ... ok
test_2_read_nested (test_confparse2.CP2Test1) ... ok
test_write (test_confparse2.CP2Test1) ... ok
test_1_ (test_taxus.TaxusTest1) ... ok
unittest.case.FunctionTestCase (_test)
Res_FormatTest_sha1sum ... ok
unittest.case.FunctionTestCase (_test)
Res_FormatTest_sha1sum ... ok
unittest.case.FunctionTestCase (_test)
Res_FormatTest_sha1sum ... ok
unittest.case.FunctionTestCase (_test)
Res_FormatTest_sha1sum ... ok
unittest.case.FunctionTestCase (_test)
Res_FormatTest_sha1sum ... ok
unittest.case.FunctionTestCase (_test)
Res_FormatTest_sha1sum ... ok

======================================================================
ERROR: test_4_lists (test_confparse.CPTest1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/project-mpe/script-mpe/test_confparse.py", line 169, in test_4_lists
    self.assertEqual(test_settings.foo.test4[0].foo, 'bar')
  File "/srv/project-mpe/script-mpe/confparse.py", line 295, in __getattr__
    return dict.__getitem__(self, name)
KeyError: 'test4'

======================================================================
ERROR: test_1_ (test_confparse.CPTest2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/project-mpe/script-mpe/test_confparse.py", line 56, in test_1_
    conf = expand_config_path(self.NAME).next()
StopIteration

======================================================================
FAIL: test_5_copy (test_confparse.CPTest1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/project-mpe/script-mpe/test_confparse.py", line 180, in test_5_copy
    'config_file': '/tmp/test1/test/sub/dir/testrc',
AssertionError: {'foo': {'bar': {'var': 'v'}, 'test4:[{foo': 'bar}]'}, 'config_file': '/tmp/test [truncated]... != {'foo': {'bar': {'var': 'v'}, 'test4': [{'foo': 'bar'}]}, 'config_file': '/tmp/t [truncated]...
  {'config_file': '/tmp/test1/test/sub/dir/testrc',
-  'foo': {'bar': {'var': 'v'}, 'test4:[{foo': 'bar}]'}}
?                                                    -

+  'foo': {'bar': {'var': 'v'}, 'test4': [{'foo': 'bar'}]}}
?                                     + +  +          +


======================================================================
FAIL: test_6_commit (test_confparse.CPTest1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/project-mpe/script-mpe/test_confparse.py", line 199, in test_6_commit
    test_settings = self.test_5_copy()
  File "/srv/project-mpe/script-mpe/test_confparse.py", line 180, in test_5_copy
    'config_file': '/tmp/test1/test/sub/dir/testrc',
AssertionError: {'foo': {'bar': {'var': 'v'}, 'test4:[{foo': 'bar}]'}, 'config_file': '/tmp/test [truncated]... != {'foo': {'bar': {'var': 'v'}, 'test4': [{'foo': 'bar'}]}, 'config_file': '/tmp/t [truncated]...
  {'config_file': '/tmp/test1/test/sub/dir/testrc',
-  'foo': {'bar': {'var': 'v'}, 'test4:[{foo': 'bar}]'}}
?                                                    -

+  'foo': {'bar': {'var': 'v'}, 'test4': [{'foo': 'bar'}]}}
?                                     + +  +          +


----------------------------------------------------------------------
Ran 22 tests in 0.045s

FAILED (failures=2, errors=2)
Coverage.py warning: Module rsr was never imported.
Coverage.py warning: Module radical was never imported.
Coverage.py warning: Module workLog was never imported.
Traceback (most recent call last):
  File "/usr/local/bin/coverage", line 9, in <module>
    load_entry_point('coverage==3.7', 'console_scripts', 'coverage')()
  File "/usr/local/lib/python2.7/dist-packages/coverage/cmdline.py", line 720, in main
    status = CoverageScript().command_line(argv)
  File "/usr/local/lib/python2.7/dist-packages/coverage/cmdline.py", line 438, in command_line
    self.do_execute(options, args)
  File "/usr/local/lib/python2.7/dist-packages/coverage/cmdline.py", line 582, in do_execute
    self.coverage.save()
  File "/usr/local/lib/python2.7/dist-packages/coverage/control.py", line 492, in save
    self._harvest_data()
  File "/usr/local/lib/python2.7/dist-packages/coverage/control.py", line 539, in _harvest_data
    py_file = self.file_locator.canonical_filename(py_file)
  File "/usr/local/lib/python2.7/dist-packages/coverage/files.py", line 46, in canonical_filename
    cf = abs_file(filename)
  File "/usr/local/lib/python2.7/dist-packages/coverage/files.py", line 118, in abs_file
    path = os.path.abspath(os.path.realpath(path))
  File "/usr/lib/python2.7/posixpath.py", line 373, in realpath
    component = join(*bits[0:i])
  File "/usr/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
KeyboardInterrupt
